sudo: required
services:
  - docker
addons:
  postgresql: "9.6"
before_script:
  - psql -c "CREATE DATABASE dienst2;" -U postgres
  - docker build --no-cache --pull -t dienst2 -t quay.io/wisvch/dienst2:$TRAVIS_BUILD_NUMBER .
script:
  - docker run --net=host --env-file ci.env dienst2 ./manage.py makemigrations --check --dry-run
  - docker run --net=host --env-file ci.env dienst2 ./manage.py test
deploy:
  provider: script
  script: sh -c 'docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io; docker push quay.io/wisvch/dienst2:$TRAVIS_BUILD_NUMBER'
  on:
    branch: master
notifications:
  slack:
    secure: Iw0CyxjbyNpxD+/TaMGb5vGt2BGzevNsqUX3fhmaUMGJc2upxPTxHZzSsYPAWlZrGj6Wt/woa8DwgKlwpwQcsdkYqOccHu3mkHum9PkgzO/chmUHUiqB0SuYtsQYO38677HJN5Ba1u60CB0+WsDHekEuIpx9TBhEV6sr3J3JqNA=
