# Generated by Django 2.2.8 on 2020-01-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldb', '0015_auto_20200109_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='board_invites',
            field=models.BooleanField(default=False, help_text='Uitnodigingen ontvangen voor bestuursactiviteiten', verbose_name='uitnodigingen bestuur'),
        ),
    ]
